### ISSUE TITLE
Add CLI, pipx support

### ISSUE THREAD

**Issue by philiporlando** [philiporlando/fgdb_to_gpkg#26]
I'm opening this issue on behalf of @brandones:

> Thanks for this nice package. I didn't see a GitHub repo link so I'm emailing you about this issue. It seems that the package doesn't package a CLI, based on the fact that I can't install it via pipx:

```
    /o/b/fgdb_to_gpkg $ pipx install fgdb-to-gpkg                                           12:04:33
    Note: Dependent package 'fiona' contains 1 apps
      - fio
    Note: Dependent package 'gdal' contains 18 apps
      - gdal2tiles.py
      - gdal2xyz.py
      - gdal_calc.py
      - gdal_edit.py
      - gdal_fillnodata.py
      - gdal_merge.py
      - gdal_pansharpen.py
      - gdal_polygonize.py
      - gdal_proximity.py
      - gdal_retile.py
      - gdal_sieve.py
      - gdalattachpct.py
      - gdalcompare.py
      - gdalmove.py
      - ogr_layer_algebra.py
      - ogrmerge.py
      - pct2rgb.py
      - rgb2pct.py
    Note: Dependent package 'charset-normalizer' contains 1 apps
      - normalizer
    Note: Dependent package 'numpy' contains 1 apps
      - f2py
    Note: Dependent package 'pyproj' contains 1 apps
      - pyproj
    Note: Dependent package 'tqdm' contains 1 apps
      - tqdm


    No apps associated with package fgdb-to-gpkg. Try again with '--include-deps' to include apps
    of dependent packages, which are listed above. If you are attempting to install a library,
    pipx should not be used. Consider using pip or a similar tool instead.
```

> Could you please add a CLI so that it's easy to run as a script without installing to the system python or manually creating a virtualenv just for that purpose? pipx is a great tool and it would be great if it was supported.
> 
> Running Ubuntu 20.04.1, pipx 1.4.3.

**Comment by brandones** [comment]
Thanks @philiporlando ! Here's some other details:

I created a virtualenv just for that purpose, and that appears not to work either:

```
/o/b/fgdb_to_gpkg [1] $ ./env/bin/python3 -m fgdb_to_gpkg ~/Downloads/my-first-project.gdb/ ~/Downloads/my-first-project.gpkg                       14:35:41
/opt/brandon/fgdb_to_gpkg/env/bin/python3: No module named fgdb_to_gpkg.__main__; 'fgdb_to_gpkg' is a package and cannot be directly executed
```

I don't know if there's some special magic that poetry does (I thought poetry was supposed to be standards-compliant?) but anyway I tried installing poetry in the virtualenv and that didn't work either:

```
/o/b/fgdb_to_gpkg [1] $ ./env/bin/poetry run python3 -m fgdb_to_gpkg ~/Downloads/my-first-project.gdb/ ~/Downloads/my-first-project.gpkg            14:37:42

Poetry could not find a pyproject.toml file in /opt/brandon/fgdb_to_gpkg or its parents
```

Hope this helps & thanks again.

**Comment by philiporlando** [comment]
> Thanks @philiporlando ! Here's some other details:
> 
> I created a virtualenv just for that purpose, and that appears not to work either:
> 
> ```
> /o/b/fgdb_to_gpkg [1] $ ./env/bin/python3 -m fgdb_to_gpkg ~/Downloads/my-first-project.gdb/ ~/Downloads/my-first-project.gpkg                       14:35:41
> /opt/brandon/fgdb_to_gpkg/env/bin/python3: No module named fgdb_to_gpkg.__main__; 'fgdb_to_gpkg' is a package and cannot be directly executed
> ```
> 
> I don't know if there's some special magic that poetry does (I thought poetry was supposed to be standards-compliant?) but anyway I tried installing poetry in the virtualenv and that didn't work either:
> 
> ```
> /o/b/fgdb_to_gpkg [1] $ ./env/bin/poetry run python3 -m fgdb_to_gpkg ~/Downloads/my-first-project.gdb/ ~/Downloads/my-first-project.gpkg            14:37:42
> 
> Poetry could not find a pyproject.toml file in /opt/brandon/fgdb_to_gpkg or its parents
> ```
> 
> Hope this helps & thanks again.

Thank you for providing these details!

My understanding of Poetry is limited, but I've only ever installed it globally using their [official installer](https://python-poetry.org/docs/#installing-with-the-official-installer) (the curl command). Poetry should create/manage its own virtual environment when using the development version of this package. I'd be curious to see if you're still seeing this `Poetry could not find a pyproject.toml file` error when installing it globally.

I should probably update the [README](https://github.com/philiporlando/fgdb_to_gpkg?tab=readme-ov-file#installing-the-development-version-of-this-package) to mention how Poetry is expected to be installed.

**Comment by philiporlando** [comment]
> I'm opening this issue on behalf of @brandones:
> 
> > Thanks for this nice package. I didn't see a GitHub repo link so I'm emailing you about this issue. It seems that the package doesn't package a CLI, based on the fact that I can't install it via pipx:
> 
> ```
>     /o/b/fgdb_to_gpkg $ pipx install fgdb-to-gpkg                                           12:04:33
>     Note: Dependent package 'fiona' contains 1 apps
>       - fio
>     Note: Dependent package 'gdal' contains 18 apps
>       - gdal2tiles.py
>       - gdal2xyz.py
>       - gdal_calc.py
>       - gdal_edit.py
>       - gdal_fillnodata.py
>       - gdal_merge.py
>       - gdal_pansharpen.py
>       - gdal_polygonize.py
>       - gdal_proximity.py
>       - gdal_retile.py
>       - gdal_sieve.py
>       - gdalattachpct.py
>       - gdalcompare.py
>       - gdalmove.py
>       - ogr_layer_algebra.py
>       - ogrmerge.py
>       - pct2rgb.py
>       - rgb2pct.py
>     Note: Dependent package 'charset-normalizer' contains 1 apps
>       - normalizer
>     Note: Dependent package 'numpy' contains 1 apps
>       - f2py
>     Note: Dependent package 'pyproj' contains 1 apps
>       - pyproj
>     Note: Dependent package 'tqdm' contains 1 apps
>       - tqdm
> 
> 
>     No apps associated with package fgdb-to-gpkg. Try again with '--include-deps' to include apps
>     of dependent packages, which are listed above. If you are attempting to install a library,
>     pipx should not be used. Consider using pip or a similar tool instead.
> ```
> 
> > Could you please add a CLI so that it's easy to run as a script without installing to the system python or manually creating a virtualenv just for that purpose? pipx is a great tool and it would be great if it was supported.
> > Running Ubuntu 20.04.1, pipx 1.4.3.

The motivation behind this project was to gain hands-on experience with Python package development. I'm excited—and pleasantly surprised—that the package has actual users! Adding CLI and `pipx` support would be a fantastic enhancement.
